// SPDX-License-Identifier: MIT
pragma solidity ^0.8.25;

import "@openzeppelin/contracts-upgradeable/token/ERC721/ERC721Upgradeable.sol";
import "@openzeppelin/contracts-upgradeable/access/AccessControlUpgradeable.sol";
import "@openzeppelin/contracts-upgradeable/utils/cryptography/EIP712Upgradeable.sol";
import "@openzeppelin/contracts-upgradeable/proxy/utils/Initializable.sol";
import "@openzeppelin/contracts/utils/cryptography/ECDSA.sol";

/// @title CommunitySBT — Soulbound Identity Passport (ERC-721)
/// @notice Non-transferable token issued to community members as a verifiable identity.
///         Uses EIP-712 typed signatures for anti-replay claim flow.
/// @dev Compatible with EIP-1167 minimal proxy pattern (clones). Never transfer/upgrade logic here.
contract CommunitySBT is
    Initializable,
    ERC721Upgradeable,
    AccessControlUpgradeable,
    EIP712Upgradeable
{
    using ECDSA for bytes32;

    // ─── Roles ────────────────────────────────────────────────────────────────
    bytes32 public constant COMMUNITY_ADMIN_ROLE = keccak256("COMMUNITY_ADMIN_ROLE");
    bytes32 public constant COMMUNITY_AFFAIR_ROLE = keccak256("COMMUNITY_AFFAIR_ROLE");

    // ─── EIP-712 Type Hash ────────────────────────────────────────────────────
    bytes32 private constant IDENTITY_CLAIM_TYPEHASH =
        keccak256("IdentityClaim(address userAddress,uint256 nonce)");

    // ─── State ────────────────────────────────────────────────────────────────
    string private _baseTokenURI;
    uint256 private _nextTokenId;

    /// @notice Tracks each user's nonce to prevent signature replay attacks.
    mapping(address => uint256) public nonce;

    /// @notice Maps user address to their token ID (at most 1 SBT per user).
    mapping(address => uint256) private _userToToken;

    // ─── Custom Errors ────────────────────────────────────────────────────────
    error Soulbound();
    error AlreadyHasSBT();
    error InvalidSignature();
    error NotAMember();

    // ─── Events ───────────────────────────────────────────────────────────────
    event IdentityClaimed(address indexed user, uint256 indexed tokenId);
    event IdentityRevoked(address indexed user, uint256 indexed tokenId);
    event BaseURIUpdated(string newBaseURI);

    // ─── Constructor ──────────────────────────────────────────────────────────

    /// @dev Disables initializers on the implementation contract to prevent
    ///      a malicious actor from calling initialize() directly on the logic contract.
    constructor() {
        _disableInitializers();
    }

    // ─── Initializer (called once per clone) ─────────────────────────────────

    /// @notice Initializes the cloned proxy as a community's SBT contract.
    /// @param tokenName     ERC-721 name (e.g., "TechClub Identity")
    /// @param tokenSymbol   ERC-721 symbol (e.g., "TCID")
    /// @param baseTokenURI  Base URI for token metadata (IPFS CID folder)
    /// @param communityAdmin Address granted COMMUNITY_ADMIN_ROLE (community head)
    /// @param superAdmin     Address granted DEFAULT_ADMIN_ROLE (CommuniGate platform)
    function initialize(
        string calldata tokenName,
        string calldata tokenSymbol,
        string calldata baseTokenURI,
        address communityAdmin,
        address superAdmin
    ) external initializer {
        __ERC721_init(tokenName, tokenSymbol);
        __AccessControl_init();
        __EIP712_init("CommuniGate", "1");

        _baseTokenURI = baseTokenURI;
        _nextTokenId = 1;

        _grantRole(DEFAULT_ADMIN_ROLE, superAdmin);
        _grantRole(COMMUNITY_ADMIN_ROLE, communityAdmin);
    }

    // ─── Member Functions ─────────────────────────────────────────────────────

    /// @notice Member calls this to claim their SBT using an off-chain EIP-712 signature.
    /// @dev The signature must be generated by an account with COMMUNITY_AFFAIR_ROLE.
    ///      Reverts if the member already holds an SBT or the signature is invalid.
    /// @param signature The EIP-712 signature produced by a Community Affair.
    function claimIdentity(bytes calldata signature) external {
        address user = msg.sender;

        if (balanceOf(user) > 0) revert AlreadyHasSBT();

        // Reconstruct the signed digest
        bytes32 digest = _hashTypedDataV4(
            keccak256(abi.encode(IDENTITY_CLAIM_TYPEHASH, user, nonce[user]))
        );

        // Recover signer and verify they hold AFFAIR role
        address signer = digest.recover(signature);
        if (!hasRole(COMMUNITY_AFFAIR_ROLE, signer)) revert InvalidSignature();

        // Anti-replay: increment nonce BEFORE minting
        nonce[user]++;

        uint256 tokenId = _nextTokenId++;
        _userToToken[user] = tokenId;
        _safeMint(user, tokenId);

        emit IdentityClaimed(user, tokenId);
    }

    // ─── Affair Functions ─────────────────────────────────────────────────────

    /// @notice Revoke (burn) a member's SBT — e.g., for rule violations.
    /// @param user The address of the member whose SBT to revoke.
    function revokeIdentity(address user) external onlyRole(COMMUNITY_AFFAIR_ROLE) {
        uint256 tokenId = _userToToken[user];
        if (tokenId == 0 || ownerOf(tokenId) != user) revert NotAMember();

        delete _userToToken[user];
        _burn(tokenId);

        emit IdentityRevoked(user, tokenId);
    }

    // ─── Admin Functions ──────────────────────────────────────────────────────

    /// @notice Update the base URI for all token metadata.
    /// @param newBaseURI The new IPFS base URI.
    function updateBaseURI(string calldata newBaseURI) external onlyRole(COMMUNITY_ADMIN_ROLE) {
        _baseTokenURI = newBaseURI;
        emit BaseURIUpdated(newBaseURI);
    }

    /// @notice Grant the COMMUNITY_AFFAIR_ROLE to an event committee member.
    function addAffair(address account) external onlyRole(COMMUNITY_ADMIN_ROLE) {
        _grantRole(COMMUNITY_AFFAIR_ROLE, account);
    }

    /// @notice Revoke the COMMUNITY_AFFAIR_ROLE from an event committee member.
    /// @dev Instantly invalidates all pending signatures from that account.
    function removeAffair(address account) external onlyRole(COMMUNITY_ADMIN_ROLE) {
        _revokeRole(COMMUNITY_AFFAIR_ROLE, account);
    }

    // ─── View Functions ───────────────────────────────────────────────────────

    /// @notice Returns the token ID owned by `user`, or 0 if they have none.
    function tokenOfOwner(address user) external view returns (uint256) {
        return _userToToken[user];
    }

    /// @notice Returns true if the user holds a valid (non-revoked) SBT.
    function isMember(address user) external view returns (bool) {
        return balanceOf(user) > 0;
    }

    /// @notice Returns the EIP-712 domain separator for this contract.
    /// @dev Used by frontends and tests to construct digests for signature verification.
    function DOMAIN_SEPARATOR() external view returns (bytes32) {
        return _domainSeparatorV4();
    }

    // ─── Soulbound Override ───────────────────────────────────────────────────

    /// @dev Blocks all transfers except minting (from == address(0))
    ///      and burning (to == address(0)) initiated by AFFAIR role.
    ///      Any other transfer attempt reverts with Soulbound().
    function _update(
        address to,
        uint256 tokenId,
        address auth
    ) internal override returns (address) {
        address from = _ownerOf(tokenId);

        // Allow: minting (from is zero)
        if (from == address(0)) {
            return super._update(to, tokenId, auth);
        }

        // Allow: burning (to is zero) — only AFFAIR role can trigger revokeIdentity
        if (to == address(0)) {
            return super._update(to, tokenId, auth);
        }

        // Block: all other transfers (wallet-to-wallet, etc.)
        revert Soulbound();
    }

    // ─── Required Overrides ───────────────────────────────────────────────────

    function _baseURI() internal view override returns (string memory) {
        return _baseTokenURI;
    }

    function supportsInterface(bytes4 interfaceId)
        public
        view
        override(ERC721Upgradeable, AccessControlUpgradeable)
        returns (bool)
    {
        return super.supportsInterface(interfaceId);
    }
}
